version: '3.8'

services:

  frontend:
    container_name: frontend
    build: ./FrontEnd
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true

  movie_api:
    container_name: movie_api
    image: docker.io/library/movie-movie_api
    ports:
      - "8080:80"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ConnectionStrings__WebApiDatabase: "Host=postgres_db; Port=5432; Database=postgres; Username=postgres; Password=postgres"
    depends_on:
      - postgres_db

  postgres_db:
    container_name: postgres_db
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./db_init:/docker-entrypoint-initdb.d/

  
